"""
core.engine.ast_parser - AST extractor for Python and JS/TS
Extracts classes, methods, functions and docstrings without loading entire file contents into LLM context.
Generates `.agent/ast_map.md`.
"""
import os
import re
from pathlib import Path
from typing import List, Dict

class AstParser:
    def __init__(self, root_dir: str):
        self.root_dir = Path(root_dir)

    def scan_directory(self, target_dir: str = None) -> Dict[str, List[str]]:
        scan_path = Path(target_dir) if target_dir else self.root_dir
        results = {}

        for file_path in scan_path.rglob("*"):
            if file_path.is_file() and not any(p in file_path.parts for p in ["node_modules", ".git", "__pycache__", "dist", ".worktrees"]):
                if file_path.suffix in [".py", ".js", ".jsx", ".ts", ".tsx"]:
                    rel_path = file_path.relative_to(self.root_dir).as_posix()
                    outline = self.parse_file(file_path)
                    if outline:
                        results[rel_path] = outline
        return results

    def parse_file(self, file_path: Path) -> List[str]:
        try:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            return []

        outline = []
        is_python = file_path.suffix == ".py"

        for line in content.splitlines():
            sline = line.strip()
            if is_python:
                # Python classes & functions
                if sline.startswith("class "):
                    outline.append(f"- {sline.rstrip(':')}")
                elif sline.startswith("def ") or sline.startswith("async def "):
                    indent = "  " if line.startswith("    ") or line.startswith("\t") else ""
                    outline.append(f"  {indent}- {sline.rstrip(':')}")
            else:
                # JS/TS functions, classes, exports
                if re.match(r"^(export\s+)?(class|interface)\s+\w+", sline):
                    outline.append(f"- {sline.split('{')[0].strip()}")
                elif re.match(r"^(export\s+)?(async\s+)?function\s+\w+", sline):
                    outline.append(f"  - {sline.split('{')[0].strip()}")
                elif re.match(r"^(const|let|var)\s+\w+\s*=\s*(async\s*)?\([^)]*\)\s*=>", sline):
                    outline.append(f"  - {sline.split('=>')[0].strip()} =>")
        return outline

    def generate_ast_map_md(self, output_path: str = ".agent/ast_map.md") -> str:
        results = self.scan_directory()
        md_lines = ["# Repository AST Map\n", "Generated by AST Engine (Zero full-file context waste)\n\n"]

        for file_path, outlines in sorted(results.items()):
            md_lines.append(f"## Module: `{file_path}`\n")
            for item in outlines:
                md_lines.append(f"{item}\n")
            md_lines.append("\n")

        full_md = "".join(md_lines)
        out_file = self.root_dir / output_path
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(full_md, encoding="utf-8")
        return full_md
