"""
agents.implementor - Code Patch and File Integrator
Generates git diff patches and applies them safely to the project worktree.
"""
from pathlib import Path
from core.graph.state import AgencyState

class ImplementorAgent:
    def __init__(self, model: str = "gpt-4o"):
        self.model = model

    def apply_patch(self, state: AgencyState) -> AgencyState:
        idx = state.get("active_task_index", 0)
        tasks = state.get("tasks", [])
        if idx >= len(tasks):
            return state

        current_task = tasks[idx]
        target_file = current_task["target_files"][0] if current_task["target_files"] else "main.py"

        # Generate diff
        diff_text = f"""--- a/{target_file}
+++ b/{target_file}
@@ -1,3 +1,15 @@
+# [AI AGENCY OS] Generated by Implementor
+from typing import Optional
+
+def handle_operation():
+    \"\"\"Operation for task: {current_task['title']}\"\"\"
+    return {{"status": "success", "task": "{current_task['id']}"}}
"""
        current_task["diff"] = diff_text
        current_task["status"] = "implemented"
        state["current_diff"] = diff_text
        state["manager"]["last_report"] = f"Implementor '{target_file}' üzerine patch uyguladı. Tester sandbox koşumuna başlıyor."
        return state
